### ISSUE TITLE
Inference stops at first save point

### ISSUE THREAD

**Issue by CJohnDesign** [AlUlkesh/sd_save_intermediate_images#8]
When I run it, it stops the generation process:
![00849-1144413703-pikachu](https://user-images.githubusercontent.com/10375280/211664310-75b86318-a7bc-4507-ad89-bc2b9989f31a.png)
![00850-3222923025-pikachu](https://user-images.githubusercontent.com/10375280/211664311-159efa0f-5550-49ec-a032-c323d3c210a4.png)
![00851-1286797252-pikachu](https://user-images.githubusercontent.com/10375280/211664313-8400ab5e-6d97-42eb-bdd4-6f2a7300321a.png)

Console doesn't come back with errors:
```
 12%|█████████▌                                                                  | 5/40 [00:04<00:31,  1.09it/s]
Total progress:  12%|███████▌                                                    | 5/40 [00:03<00:26,  1.30it/s]

```

**Comment by AlUlkesh** [comment]
Just tried this, works for me:
```
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [00:07<00:00,  5.26it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████▉| 719/720 [2:23:10<00:11, 11.95s/it]

```
<img src="https://user-images.githubusercontent.com/99896447/211680944-31702da9-ac99-4309-b591-ddd67979ffee.png" width="64">
<img src="https://user-images.githubusercontent.com/99896447/211680950-3c5320a8-0e01-4120-976d-6fd5c90ae0b9.png" width="64">
<img src="https://user-images.githubusercontent.com/99896447/211680952-ee32c3cf-2353-45cf-ab8c-801707b4d7ff.png" width="64">
<img src="https://user-images.githubusercontent.com/99896447/211680953-98bafbd8-1344-42b3-8130-6f93553ce2e3.png" width="64">
<img src="https://user-images.githubusercontent.com/99896447/211680954-cfcf1ccc-c349-4ccd-a775-8b132be7dee0.png" width="64">
<img src="https://user-images.githubusercontent.com/99896447/211680957-6f919580-98c9-4ab4-932c-484ab57699fa.png" width="64">
<img src="https://user-images.githubusercontent.com/99896447/211680958-da4d94c9-629c-4e81-b86b-a81f48f5c674.png" width="64">
I'm not sure where to start looking for your issue, since you don't get any error messages.

Can you share the full console output starting from starting webui-user?

**Comment by AlUlkesh** [comment]
I just saw that about the same time you reported this, a faulty commit was merged on the webui repository. This was fixed an hour ago. Perhaps try a git pull and see if you just happened to run into that timeframe.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/9cfd10cdefc7b2966b8e42fbb0e05735967cf87b

**Comment by CJohnDesign** [comment]
So its not throwing that error anymore but its not showing the progress. No console errors. I did check the box and left the settings default. 

I'm running it locally on an M1 Max laptop with 32gb of shared memory

**Comment by CJohnDesign** [comment]
its not saving to the output folder either

**Comment by CJohnDesign** [comment]
Ok, got them saving to exports. Is it supposed to show a preview as it saves?

**Comment by CJohnDesign** [comment]
Got it working! Here's the debug output just in case
```
2023-01-11 09:39:48,144 DEBUG ssii_intermediate_type, ssii_every_n, ssii_stop_at_n: Denoised, 5.0, 0.0 1.05it/s]
2023-01-11 09:39:48,144 DEBUG Step: 15
2023-01-11 09:39:48,144 DEBUG hr: False
2023-01-11 09:39:48,784 DEBUG ssii_intermediate_type, ssii_every_n, ssii_stop_at_n: Denoised, 5.0, 0.0
2023-01-11 09:39:48,784 DEBUG Step: 15
2023-01-11 09:39:48,940 DEBUG filename: 00865-015-1555154292-%%%%%%%
 80%|████████████████████████████████████████████████████████████               | 16/20 [00:18<00:04,  1.17s/it]2023-01-11 09:39:49,882 DEBUG ssii_intermediate_type, ssii_every_n, ssii_stop_at_n: Denoised, 5.0, 0.0 1.17s/it]
2023-01-11 09:39:49,882 DEBUG Step: 16
2023-01-11 09:39:49,882 DEBUG hr: False
 85%|███████████████████████████████████████████████████████████████▊           | 17/20 [00:19<00:03,  1.10s/it]2023-01-11 09:39:50,753 DEBUG ssii_intermediate_type, ssii_every_n, ssii_stop_at_n: Denoised, 5.0, 0.0 1.10s/it]
2023-01-11 09:39:50,753 DEBUG Step: 17
2023-01-11 09:39:50,753 DEBUG hr: False
```
 
Closing this issue
